ls:
  packages/*:
    .ts: camelCase
    .spec.ts: camelCase
    .config.ts: camelCase
    .less: camelCase
    .vue: PascalCase
    .md: PascalCase
    .zh.md: PascalCase
    .en.md: PascalCase

  scripts:
    .ts: camelCase
    .svg: kebab-case

ignore:
  - packages/components/i18n/src/locales
