/**
 * @license
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/IDuxFE/idux/blob/main/LICENSE
 */

declare module 'vue' {
  export interface GlobalComponents {
    IxAlert: typeof import('@idux/components/alert')['IxAlert']
    IxAnchor: typeof import('@idux/components/anchor')['IxAnchor']
    IxAnchorLink: typeof import('@idux/components/anchor')['IxAnchorLink']
    IxAvatar: typeof import('@idux/components/avatar')['IxAvatar']
    IxBackTop: typeof import('@idux/components/back-top')['IxBackTop']
    IxBadge: typeof import('@idux/components/badge')['IxBadge']
    IxButton: typeof import('@idux/components/button')['IxButton']
    IxButtonGroup: typeof import('@idux/components/button')['IxButtonGroup']
    IxCard: typeof import('@idux/components/card')['IxCard']
    IxCardGrid: typeof import('@idux/components/card')['IxCardGrid']
    IxCheckbox: typeof import('@idux/components/checkbox')['IxCheckbox']
    IxCheckboxGroup: typeof import('@idux/components/checkbox')['IxCheckboxGroup']
    IxCol: typeof import('@idux/components/grid')['IxCol']
    IxCollapse: typeof import('@idux/components/collapse')['IxCollapse']
    IxCollapsePanel: typeof import('@idux/components/collapse')['IxCollapsePanel']
    IxDatePicker: typeof import('@idux/components/date-picker')['IxDatePicker']
    IxDivider: typeof import('@idux/components/divider')['IxDivider']
    IxDrawer: typeof import('@idux/components/drawer')['IxDrawer']
    IxDrawerProvider: typeof import('@idux/components/drawer')['IxDrawerProvider']
    IxDropdown: typeof import('@idux/components/dropdown')['IxDropdown']
    IxEmpty: typeof import('@idux/components/empty')['IxEmpty']
    IxForm: typeof import('@idux/components/form')['IxForm']
    IxFormItem: typeof import('@idux/components/form')['IxFormItem']
    IxFormWrapper: typeof import('@idux/components/form')['IxFormWrapper']
    IxHeader: typeof import('@idux/components/header')['IxHeader']
    IxIcon: typeof import('@idux/components/icon')['IxIcon']
    IxImage: typeof import('@idux/components/image')['IxImage']
    IxInput: typeof import('@idux/components/input')['IxInput']
    IxInputNumber: typeof import('@idux/components/input-number')['IxInputNumber']
    IxLayout: typeof import('@idux/components/layout')['IxLayout']
    IxLayoutContent: typeof import('@idux/components/layout')['IxLayoutContent']
    IxLayoutFooter: typeof import('@idux/components/layout')['IxLayoutFooter']
    IxLayoutHeader: typeof import('@idux/components/layout')['IxLayoutHeader']
    IxLayoutPro: typeof import('@idux/pro/layout')['IxLayoutPro']
    IxLayoutSider: typeof import('@idux/components/layout')['IxLayoutSider']
    IxLayoutSiderTrigger: typeof import('@idux/pro/layout')['IxLayoutSiderTrigger']
    IxList: typeof import('@idux/components/list')['IxList']
    IxListItem: typeof import('@idux/components/list')['IxListItem']
    IxMenu: typeof import('@idux/components/menu')['IxMenu']
    IxMenuDivider: typeof import('@idux/components/menu')['IxMenuDivider']
    IxMenuItem: typeof import('@idux/components/menu')['IxMenuItem']
    IxMenuItemGroup: typeof import('@idux/components/menu')['IxMenuItemGroup']
    IxMenuSub: typeof import('@idux/components/menu')['IxMenuSub']
    IxMessageProvider: typeof import('@idux/components/message')['IxMessageProvider']
    IxModal: typeof import('@idux/components/modal')['IxModal']
    IxModalProvider: typeof import('@idux/components/modal')['IxModalProvider']
    IxNotificationProvider: typeof import('@idux/components/notification')['IxNotificationProvider']
    IxPagination: typeof import('@idux/components/pagination')['IxPagination']
    IxPopconfirm: typeof import('@idux/components/popconfirm')['IxPopconfirm']
    IxPopover: typeof import('@idux/components/popover')['IxPopover']
    IxProgress: typeof import('@idux/components/progress')['IxProgress']
    IxRadio: typeof import('@idux/components/radio')['IxRadio']
    IxRadioGroup: typeof import('@idux/components/radio')['IxRadioGroup']
    IxRate: typeof import('@idux/components/rate')['IxRate']
    IxResult: typeof import('@idux/components/result')['IxResult']
    IxRow: typeof import('@idux/components/grid')['IxRow']
    IxSelect: typeof import('@idux/components/select')['IxSelect']
    IxSelectOption: typeof import('@idux/components/select')['IxSelectOption']
    IxSelectOptionGroup: typeof import('@idux/components/select')['IxSelectOptionGroup']
    IxSkeleton: typeof import('@idux/components/skeleton')['IxSkeleton']
    IxSpace: typeof import('@idux/components/space')['IxSpace']
    IxSpin: typeof import('@idux/components/spin')['IxSpin']
    IxStatistic: typeof import('@idux/components/statistic')['IxStatistic']
    IxStepper: typeof import('@idux/components/stepper')['IxStepper']
    IxStepperItem: typeof import('@idux/components/stepper')['IxStepperItem']
    IxSwitch: typeof import('@idux/components/switch')['IxSwitch']
    IxTab: typeof import('@idux/components/tabs')['IxTab']
    IxTable: typeof import('@idux/components/table')['IxTable']
    IxTabs: typeof import('@idux/components/tabs')['IxTabs']
    IxTag: typeof import('@idux/components/tag')['IxTag']
    IxTextarea: typeof import('@idux/components/textarea')['IxTextarea']
    IxTimeline: typeof import('@idux/components/timeline')['IxTimeline']
    IxTimelineItem: typeof import('@idux/components/timeline')['IxTimelineItem']
    IxTimePicker: typeof import('@idux/components/time-picker')['IxTimePicker']
    IxTooltip: typeof import('@idux/components/tooltip')['IxTooltip']
    IxTree: typeof import('@idux/components/tree')['IxTree']
  }
}

export {}
