// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    GlobalCodeBox: typeof import('./src/components/global/GlobalCodeBox.vue')['default']
    GlobalColors: typeof import('./src/components/global/GlobalColors.vue')['default']
    Home: typeof import('./src/components/views/home/Home.vue')['default']
    IxAffix: typeof import('@idux/components/affix')['IxAffix']
    IxAnchor: typeof import('@idux/components/anchor')['IxAnchor']
    IxAnchorLink: typeof import('@idux/components/anchor')['IxAnchorLink']
    IxButton: typeof import('@idux/components/button')['IxButton']
    IxButtonGroup: typeof import('@idux/components/button')['IxButtonGroup']
    IxCol: typeof import('@idux/components/grid')['IxCol']
    IxDropdown: typeof import('@idux/components/dropdown')['IxDropdown']
    IxIcon: typeof import('@idux/components/icon')['IxIcon']
    IxInput: typeof import('@idux/components/input')['IxInput']
    IxLayout: typeof import('@idux/components/layout')['IxLayout']
    IxLayoutContent: typeof import('@idux/components/layout')['IxLayoutContent']
    IxLayoutFooter: typeof import('@idux/components/layout')['IxLayoutFooter']
    IxLayoutHeader: typeof import('@idux/components/layout')['IxLayoutHeader']
    IxLayoutSider: typeof import('@idux/components/layout')['IxLayoutSider']
    IxMenu: typeof import('@idux/components/menu')['IxMenu']
    IxMenuItem: typeof import('@idux/components/menu')['IxMenuItem']
    IxMenuItemGroup: typeof import('@idux/components/menu')['IxMenuItemGroup']
    IxMenuSub: typeof import('@idux/components/menu')['IxMenuSub']
    IxMessageProvider: typeof import('@idux/components/message')['IxMessageProvider']
    IxModalProvider: typeof import('@idux/components/modal')['IxModalProvider']
    IxPortal: typeof import('@idux/cdk/portal')['IxPortal']
    IxRow: typeof import('@idux/components/grid')['IxRow']
    IxSpace: typeof import('@idux/components/space')['IxSpace']
    IxTooltip: typeof import('@idux/components/tooltip')['IxTooltip']
    LayoutFooter: typeof import('./src/components/layout/footer/LayoutFooter.vue')['default']
    LayoutFooterCol: typeof import('./src/components/layout/footer/LayoutFooterCol.vue')['default']
    LayoutFooterItem: typeof import('./src/components/layout/footer/LayoutFooterItem.vue')['default']
    LayoutHeader: typeof import('./src/components/layout/header/LayoutHeader.vue')['default']
    LayoutHeaderGithubButton: typeof import('./src/components/layout/header/LayoutHeaderGithubButton.vue')['default']
    LayoutHeaderLogo: typeof import('./src/components/layout/header/LayoutHeaderLogo.vue')['default']
    LayoutHeaderNavigation: typeof import('./src/components/layout/header/LayoutHeaderNavigation.vue')['default']
    LayoutHeaderSearchBox: typeof import('./src/components/layout/header/LayoutHeaderSearchBox.vue')['default']
    LayoutSider: typeof import('./src/components/layout/LayoutSider.vue')['default']
  }
}

export { }
