import type { IconDefinition } from './types'

import {
  Up,
  Down,
  Left,
  Right,
  Loading,
  Empty,
  RotateLeft,
  RotateRight,
  ZoomIn,
  ZoomOut,
  Close,
  Check,
  CheckCircle,
  CloseCircle,
  CloseCircleFilled,
  CheckCircleFilled,
  InfoCircle,
  InfoCircleFilled,
  ExclamationCircleFilled,
  ExclamationCircle,
  Star,
  VerticalAlignTop,
  Ellipsis,
  QuestionCircle,
  DoubleLeft,
  DoubleRight,
} from './definitions'

export const staticIcons: IconDefinition[] = [
  Up,
  Down,
  Left,
  Right,
  DoubleLeft,
  DoubleRight,
  Loading,
  Empty,
  RotateLeft,
  RotateRight,
  ZoomIn,
  ZoomOut,
  Check,
  CheckCircle,
  CheckCircleFilled,
  Close,
  CloseCircle,
  CloseCircleFilled,
  InfoCircle,
  InfoCircleFilled,
  ExclamationCircleFilled,
  ExclamationCircle,
  Star,
  VerticalAlignTop,
  Ellipsis,
  QuestionCircle,
]
